### ISSUE TITLE
Почитать комментарии к коммиту

### ISSUE THREAD

**Issue by shtirlizc** [DonIkOt/Front_MPS_Eleynik#2]
https://github.com/DonIkOt/Front_MPS_Eleynik/commit/36912d548e270852ce001331210f35b270033d00#diff-a30d0742aca80c625ae186b1101ef4ff7ecbb2184a7da832b85a6d4a4f533606L14

**Comment by DonIkOt** [comment]
Прочитал, учту в будущем, но здесь уже не буду ничего менять.
