### ISSUE TITLE
Фиксы

### ISSUE THREAD

**Issue by shtirlizc** [DonIkOt/Front_MPS_Eleynik#8]
- [x] Стили шапки и подвала - подумать
- [x] Боковые отступы в блоках сделать ближе к макету
- [x] Работы - убрать фон и сделать ближе к макету
- [x] Контакты - отрефакторить без vh
- [x] Тайтлы - подумать

**Comment by DonIkOt** [comment]
Неидеально, но принял меры по всем фиксам.
