### ISSUE TITLE
JS Задание 2

### ISSUE THREAD

**Issue by shtirlizc** [DonIkOt/Front_MPS_Eleynik#9]
https://github.com/DonIkOt/Front_MPS_Eleynik/blob/e6e53b388101ef154d55311946125cf77eb45e21/java.js#L99

Можно ведь одним запросом получить сразу 10 цитат - https://programming-quotesapi.vercel.app/api/bulk

Это место предлагаю переделать, а бан запросов, возможно был связан с ограничением количества запросов в час
В остальном все хорошо, вариант с фильтрацией из текущего списка тоже подойдет

**Comment by DonIkOt** [comment]
done
